experiment_name: zero_shot_evaluation_ModelNet40
debug: True
device: 0
model_devices: [0]
force_cpu: False

checkpoint_name: checkpoint_name

# Defined for compatibility
training:
  seed: 42
  epochs: 100
  checkpoint_every_n_samples: 0
  lr: 0.0001
  batch_size: 16
  gradient_accumulation_steps: 1
  num_workers: 16

dataset:
  name: ModelNet40
  has_colors: False
  train_path: modelnet40_preprocessed/train/
  test_path: modelnet40_preprocessed/test/
  dataset_pct: 1.0
